# Build step #1: build the React front end
FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY frontend/package.json frontend/package-lock.json ./
RUN npm install

COPY frontend/craco.config.js frontend/tailwind.config.js ./
COPY ./frontend/src ./src
COPY ./frontend/public ./public

RUN npm run build

# Build step #2: build an nginx container
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY deployment/nginx.conf /etc/nginx/conf.d/default.conf